### ISSUE TITLE
Text on the Welcome page is )^:

### ISSUE THREAD

**Issue by millaangell** [elifoster/luser-interface#1]
Some of the text on the Welcome page looks bad against the background color. The tones makes me sad. The [Note](http://puu.sh/ljKMs/7c60279fef.png) bit of text is ugh :mask: . Actually, the text in the dark gray is just [causing](http://puu.sh/ljL8t/772efd076a.png) a [lot](http://puu.sh/ljL9R/a59db746c5.png) of aesthetic [issues](http://puu.sh/ljLdl/e7fe53ddc4.png) all around in the areas w/ lighter background.
We should change that.

Eli edit:
- [x] text-color-subtle: The text being too dark
- [x] Search placeholder text color: Too dark
- [x] Icons: Too dark

**Comment by elifoster** [comment]
I believe the variable needing to be changed for this is text-color-subtle, which is currently set to #555.
